services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qgisserver
    ports:
      - "4000:4000"
  qgisserver:
    image: qgis/qgis-server:latest
    volumes:
      - ./:/io/data
    environment:
      - QGIS_SERVER_LOG_LEVEL=0
      - QGIS_USER=1000
  mapproxy:
    image: kartoza/mapproxy
    volumes:
      - ./mapproxy:/mapproxy
    ports:
      - "4001:8080"
  mviewer:
    image: mviewer/mviewer
    volumes:
      - ./mviewer:/usr/share/nginx/html/apps
    ports:
      - "8080:8080"
